### ISSUE TITLE
function :photo.__struct__/0 is undefined (module :photo is not available)

### ISSUE THREAD

**Issue by mpugach** [zhyu/nadia#53]
```
Nadia.get_chat MY_TELEGRAM_USER_ID
** (UndefinedFunctionError) function :photo.__struct__/0 is undefined (module :photo is not available)
    :photo.__struct__()
    (elixir) lib/kernel.ex:1791: Kernel.struct/3
    (nadia) lib/nadia/parser.ex:53: Nadia.Parser.parse/1
    (elixir) lib/enum.ex:1274: anonymous fn/3 in Enum.map/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1843: Enum.map/2
    (nadia) lib/nadia/parser.ex:41: Nadia.Parser.parse/2
    (nadia) lib/nadia/api.ex:32: Nadia.API.process_response/2```

**Comment by rockneurotiko** [comment]
The problem is that the field `:photo` are only parsed if it's an array, if it's a single value it falls back to this line: https://github.com/zhyu/nadia/blob/master/lib/nadia/parser.ex#L41

And, we can see, that the model `GetChat` have a field `photo` with a single value: https://core.telegram.org/bots/api#chat

So... It goes to that fallback and tries to build the struct with the atom `:photo`, which it's not a struct 😄 

Possible solution: 
- Add the model ChatPhoto: https://core.telegram.org/bots/api#chatphoto
- Add the line to parse it, under the one that parses when it's a list: `def parse(:photo, val), do: parse(ChatPhoto, val)`

**Comment by rockneurotiko** [comment]
This is not fixed yet, I'll make the PR later today (I didn't fixed it because I wanted to split the format & the fix 😄 )
